name: Docker Build and Push

on:
  push:
    branches: [ main, develop ]
  workflow_run:
    workflows: [ "Rudis CI", "Spring Boot CI", "Integration Test" ]
    types: [ completed ]
    branches: [ main, develop ]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Rudis image
        uses: docker/build-push-action@v5
        with:
          context: ./rudis
          push: false
          tags: rudis:latest

      - name: Build Spring Boot image
        uses: docker/build-push-action@v5
        with:
          context: ./be
          push: false
          tags: spring-boot-tester:latest